---
- hosts: misc_infrastructure
  become: yes
  gather_facts: yes
  roles: 
    - misc-infrastructure
    - metrics-monitor/agent
  vars:
    agent:
      rabbitmq:
        enabled: true
      docker:
        enabled: true
      redis:
        enabled: true
      statsd:
        enabled: true
  tags:
    - misc-infrastructure

