plugin: aws_ec2
regions:
  - eu-west-1
#groups:
#  flink_task_manager: "'flink-task-manager' in name"
#  flink_job_manager: "'flink-job-manager' in name"
#  metrics_dashboard: "'metrics-dashboard' in name"
#  kafka_node: "'kafka-node' in name"
#  kafka_stream: "'kafka-stream' in name"
#  storm_nimbus: "'storm-nimbus' in name"
#  storm_supervisor: "'storm-supervisor' in name"
#  misc_infrastructure: "'misc-infrastructure' in name"