---
- name: Deploy GiraGen Generator
  include_role:
    name: container/docker/compose
  vars:
    compose:
      src: /opt/impads/containers
      name: giragen
      services:
        - name: giragen-generator
          image: impads/giragen-generator:0.0.1-SNAPSHOT
          container_name: giragen-generator
          properties:
            - { src: application.conf.j2, from: application.conf, to: /opt/isel/thesis/impads/spds-benchmark/giragen/conf/application.conf }
          files:
            - { src: "{{ playbook_dir }}/../../../spds-data/viagens_gira_2018.csv", from: viagens_gira_2018.csv, to: /opt/isel/thesis/impads/spds-benchmark/giragen/data/viagens_gira_2018.csv }
            - { src: "{{ playbook_dir }}/../../../spds-data/waze_irregularidades_2018.csv", from: waze_irregularidades_2018.csv, to: /opt/isel/thesis/impads/spds-benchmark/giragen/data/waze_irregularidades_2018.csv }
            - { src: "{{ playbook_dir }}/../../../spds-data/waze_jams_2018.csv", from: waze_jams_2018.csv, to: /opt/isel/thesis/impads/spds-benchmark/giragen/data/waze_jams_2018.csv }