---
- hosts: storm_nimbus
  become: yes
  gather_facts: yes
  serial: 1
  roles:
    - storm-infrastructure/nimbus
  tags:
    - storm-nimbus

- hosts: storm_supervisor
  become: yes
  gather_facts: yes
  roles:
    - storm-infrastructure/supervisor
    - metrics-monitor/agent
  vars:
    agent:
      statsd:
        enabled: true
      docker:
        enabled: true
  tags:
    - storm-supervisor


