---
- hosts: flink_job_manager
  become: yes
  gather_facts: yes
  serial: 1
  roles:
    - flink-infrastructure/job-manager
  vars:
    flink_services:
      flink_job_manager_address: "{{ hostvars['flink-job-manager-0']['network_interfaces'][0]['private_ip_address'] }}"
  tags:
    - flink-job-manager

- hosts: flink_task_manager
  become: yes
  gather_facts: yes
  roles:
    - flink-infrastructure/task-manager
    - metrics-monitor/agent
  vars:
    flink_services:
      flink_job_manager_address: "{{ hostvars['flink-job-manager-0']['network_interfaces'][0]['private_ip_address'] }}"
      flink_task_manager_address: "{{ hostvars[ansible_hostname]['network_interfaces'][0]['private_ip_address'] }}"
    agent:
      outputs:
        influxdb:
          host: "http://{{ hostvars['metrics-dashboard-0']['network_interfaces'][0]['private_ip_address'] }}:8086"
      statsd:
        enabled: true
      docker:
        enabled: true
      jmx:
        enabled: true
        host: task-manager
  tags:
    - flink-task-manager

- hosts: misc_infrastructure
  become: yes
  gather_facts: yes
  tasks:
    - name: Run Redis List Consumer for Flink output data
      command:
        cmd: "docker run -d --rm --network container:redis impads/redis-list-consumer:0.0.1 -rh localhost -rk flink_output"