---
- hosts: misc_infrastructure
  become: yes
  gather_facts: yes
  roles: 
    - misc-infrastructure
    - metrics-monitor/agent
  vars:
    agent:
      outputs:
        influxdb:
          host: "http://{{ hostvars['metrics-dashboard-0']['network_interfaces'][0]['private_ip_address'] }}:8086"
      rabbitmq:
        enabled: true
        host: "http://{{ hostvars['misc-infrastructure-0']['network_interfaces'][0]['private_ip_address'] }}:8080"
      docker:
        enabled: true
      redis:
        enabled: true
        host: "{{ hostvars['misc-infrastructure-0']['network_interfaces'][0]['private_ip_address'] }}:6379"
      statsd:
        enabled: true
  tags:
    - misc-infrastructure

- hosts: misc_infrastructure
  become: yes
  gather_facts: yes
  tasks:
    - name: Populate Redis with IPMA Values
      command:
        cmd: "docker run --rm --network container:redis impads/ipma-data-to-redis:0.0.1 -rh localhost"
  tags:
    - ipma-data-to-redis

- hosts: misc_infrastructure
  become: yes
  gather_facts: yes
  tasks:
    - name: Defined Key for Flink Output data
      set_fact:
        redis_key: flink_output
      when: hostvars['flink-job-manager-0'] is defined
    - name: Defined Key for Storm Output data
      set_fact:
        redis_key: storm_output
      when: hostvars['storm-nimbus-0'] is defined
    - name: Defined Key for Kafka Streams Output data
      set_fact:
        redis_key: kafka_result
      when: hostvars['kafka-node-0'] is defined
    - name: Run Redis List Consumer for Flink output data
      command:
        cmd: "docker run -d --rm --name redis-list-consumer-{{ redis_key }} --network container:redis impads/redis-list-consumer:0.0.1 -rh localhost -rk {{ redis_key }}"
      when: redis_key is defined
  tags:
    - redis-list-consumer

