---

- hosts: kafka_node
  become: yes
  gather_facts: yes
  serial: 1
  roles:
    - kafka-infrastructure/kafka
    - metrics-monitor/agent
  vars:
    kafka_services:
      kafka_external_address: "{{ hostvars[ansible_hostname]['network_interfaces'][0]['private_ip_address'] }}"
    agent:
      outputs:
        influxdb:
          host: "http://{{ hostvars['metrics-dashboard-0']['network_interfaces'][0]['private_ip_address'] }}:8086"
      statsd:
        enabled: true
      docker:
        enabled: true
      jmx:
        enabled: true
        host: kafka
  tags:
    - kafka