---
- hosts: storm_nimbus
  become: yes
  gather_facts: yes
  serial: 1
  roles:
    - storm-infrastructure/nimbus
  vars:
    storm_services:
      storm_nimbus_address: "{{ hostvars['storm-nimbus-0']['network_interfaces'][0]['private_ip_address'] }}"
  tags:
    - storm-nimbus

- hosts: storm_supervisor
  become: yes
  gather_facts: yes
  roles:
    - storm-infrastructure/supervisor
    - metrics-monitor/agent
  vars:
    storm_services:
      storm_nimbus_address: "{{ hostvars['storm-nimbus-0']['network_interfaces'][0]['private_ip_address'] }}"
      storm_supervisor_address: "{{ hostvars[ansible_hostname]['network_interfaces'][0]['private_ip_address'] }}"
    agent:
      outputs:
        influxdb:
          host: "http://{{ hostvars['metrics-dashboard-0']['network_interfaces'][0]['private_ip_address'] }}:8086"
      statsd:
        enabled: true
      docker:
        enabled: true
      jmx:
        enabled: true
        host: supervisor
  tags:
    - storm-supervisor


- hosts: misc_infrastructure
  become: yes
  gather_facts: yes
  tasks:
    - name: Run Redis List Consumer for Kafka Streams output data
      command:
        cmd: "docker run -d --rm --network container:redis impads/redis-list-consumer:0.0.1 -rh localhost -rk storm_output"

