---
- hosts: storm_nimbus
  become: yes
  gather_facts: yes
  serial: 1
  roles:
    - storm-infrastructure/nimbus
  vars:
    storm_services:
      storm_nimbus_address: "{{ hostvars['storm-nimbus-0']['network_interfaces'][0]['private_ip_address'] }}"
  tags:
    - storm-nimbus

- hosts: storm_supervisor
  become: yes
  gather_facts: yes
  roles:
    - { role: storm-infrastructure/supervisor, tags: supervisor }
    - { role: metrics-monitor/agent, tags: agent }
  vars:
    storm_services:
      storm_nimbus_address: "{{ hostvars['storm-nimbus-0']['network_interfaces'][0]['private_ip_address'] }}"
      storm_supervisor_address: "{{ hostvars[ansible_hostname]['network_interfaces'][0]['private_ip_address'] }}"
    agent:
      outputs:
        influxdb:
          host: "http://{{ hostvars['metrics-dashboard-0']['network_interfaces'][0]['private_ip_address'] }}:8086"
      statsd:
        enabled: true
      docker:
        enabled: true
      jmx:
        enabled: true
        host: supervisor
        multi_agents:
          enabled: true
          ports:
            - 16700
            - 16701
            - 16702
            - 16703
            - 16704
            - 16705
            - 16706
            - 16707
  tags:
    - storm-supervisor

