---
- hosts: misc_infrastructure
  become: yes
  gather_facts: yes
  roles:
    - giragen
  vars:
    giragen:
      throughput: 1300
      rabbitmq:
        host: "{{ hostvars['misc-infrastructure-0']['network_interfaces'][0]['private_ip_address'] }}"
      telegraf:
        host: "{{ hostvars['misc-infrastructure-0']['network_interfaces'][0]['private_ip_address'] }}"
  tags:
    - giragen