---
- hosts: flink_job_manager
  become: yes
  gather_facts: yes
  serial: 1
  roles:
    - topology-submitter/flink-job-submitter
  vars:
    flink_job:
      from: "{{ playbook_dir }}/../files/spds-flink/jobs/spds-flink-gira-topology-shaded.jar"
      name: "spds-flink-gira-topology-shaded.jar"
    flink_job_arguments: "--config.file.path /opt/impads/flink/jobs/flink-gira-topology.conf"
    flink_job_config_files:
      - { from: "{{ playbook_dir }}/../files/spds-flink/jobs/flink-gira-topology.conf", to: "/opt/impads/flink/jobs/flink-gira-topology.conf"}
    flink_job_configs_vars:
      parallelism: 32
      until_phase: RESULT
      rabbitmq:
        host: "{{ hostvars['misc-infrastructure-0']['network_interfaces'][0]['private_ip_address'] }}"
      redis:
        host: "{{ hostvars['misc-infrastructure-0']['network_interfaces'][0]['private_ip_address'] }}"


  tags:
    - flink-job-submit-gira-topology