---
- hosts: kafka-node-0
  become: yes
  gather_facts: yes
  roles:
    - kafka-infrastructure/kafka-operations
  vars:
    kafka_bootstrap_server: "{{ hostvars['kafka-node-0']['network_interfaces'][0]['private_ip_address'] }}:9092"
    kafka_operations:
      create_topics:
        topics:
          - name: "gira_travels"
            partitions: 32
          - name: "waze_jams"
            partitions: 32
          - name: "waze_irregularities"
            partitions: 32
          - name: "kafka_result"
            partitions: 32
      restart_consumer_groups:
        execute: true
      streams_applications_reset:
        execute: true
        application_id: gira-travels-pattern
  tags:
    - kafka-operations-create-topics

- hosts: kafka_node
  become: yes
  gather_facts: yes
  roles:
    - kafka-infrastructure/kafka-connect
  vars:
    kafka_bootstrap_server: "{{ hostvars['kafka-node-0']['network_interfaces'][0]['private_ip_address'] }}:9092"
    kafka_connectors:
      rabbitmq:
        host: "{{ hostvars['misc-infrastructure-0']['network_interfaces'][0]['private_ip_address'] }}"
      redis:
        mocked: false
        host: "{{ hostvars['misc-infrastructure-0']['network_interfaces'][0]['private_ip_address'] }}"
  tags:
    - kafka-connect

- hosts: kafka_stream
  become: yes
  gather_facts: yes
  roles:
      - topology-submitter/kafka-stream-job-submitter
      - metrics-monitor/agent
  vars:
    kafka_bootstrap_server: "{{ hostvars['kafka-node-0']['network_interfaces'][0]['private_ip_address'] }}:9092"
    kafka_stream_configs_vars:
      parallelism: 32
      until_phase: OUTPUT
      redis:
        host: "{{ hostvars['misc-infrastructure-0']['network_interfaces'][0]['private_ip_address'] }}"
    agent:
      outputs:
        influxdb:
          host: "http://{{ hostvars['metrics-dashboard-0']['network_interfaces'][0]['private_ip_address'] }}:8086"
      statsd:
        enabled: true
      docker:
        enabled: true
      jmx:
        enabled: true
        host: kafka-stream
  tags:
      - kafka-stream-job-submit-gira-topology