---
- hosts: kafka-node-0
  become: yes
  gather_facts: yes
  roles:
    - kafka-infrastructure/kafka-operations
  vars:
    kafka_operations:
      create_topics:
        topics:
          - name: "gira_travels"
            partitions: 1
          - name: "waze_jams"
            partitions: 1
          - name: "waze_irregularities"
            partitions: 1
          - name: "kafka_result"
            partitions: 1
      restart_consumer_groups:
        execute: true
      streams_applications_reset:
        execute: true
        application_id: gira-travels-pattern
  tags:
    - kafka-operations-create-topics

- hosts: kafka_node
  become: yes
  gather_facts: yes
  roles:
    - kafka-infrastructure/kafka-connect
  tags:
    - kafka-connect

- hosts: kafka_stream
  become: yes
  gather_facts: yes
  serial: 1
  roles:
      - topology-submitter/kafka-stream-job-submitter
      - metrics-monitor/agent
  vars:
    agent:
      statsd:
        enabled: true
      docker:
        enabled: true
  tags:
      - kafka-stream-job-submit-gira-topology