---
- hosts: storm_nimbus
  become: yes
  gather_facts: yes
  serial: 1
  roles:
    - topology-submitter/storm-job-submitter
  vars:
    storm_job:
      from: "{{ playbook_dir }}/../files/spds-storm/jobs/spds-storm-gira-topology-shaded.jar"
      name: "spds-storm-gira-topology-shaded.jar"
    storm_job_main_classpath: org.isel.thesis.impads.storm.topology.MainStormGiraTopology
    storm_job_arguments: /opt/impads/storm/jobs/storm-gira-topology.conf
    storm_job_config_files:
      - { from: "{{ playbook_dir }}/../files/spds-storm/jobs/storm-gira-topology.conf", to: "/opt/impads/storm/jobs/storm-gira-topology.conf"}
    storm_job_configs_vars:
      parallelism: 8
      until_phase: OUTPUT
      rabbitmq:
        host: "{{ hostvars['misc-infrastructure-0']['network_interfaces'][0]['private_ip_address'] }}"
      redis:
        host: "{{ hostvars['misc-infrastructure-0']['network_interfaces'][0]['private_ip_address'] }}"
  tags:
    - storm-job-submit-gira-topology