---
- name: Deploy Metrics Agent
  include_role:
    name: container/docker/compose
  vars:
    compose:
      src: /opt/impads/containers
      name: metrics-agent
      services:
        - name: telegraf
          image: telegraf:1.17-alpine
          container_name: telegraf
          ports:
            - "8125:8125/udp"
          properties:
            - { src: telegraf.conf.j2, from: telegraf.conf, to: /etc/telegraf/telegraf.conf }
          volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"