---
- name: Deploy Flink Task Manager
  include_role:
    name: container/docker/compose
  vars:
    compose:
      src: /opt/impads/containers
      name: flink-task-manager
      services:
        - name: task-manager
          image: flink:1.11.1-scala_2.12-java11
          container_name: task-manager
          command: taskmanager
          ports:
            - "6121:6121"
            - "6122:6122"
            - "6124:6124"
            - "6125:6125"
            - "40100:40100"
            - "50100:50100"
          environment:
            - JOB_MANAGER_RPC_ADDRESS={{ flink_services.flink_job_manager_address }}
          properties:
            - { src: flink-conf.yaml.j2, from: flink-conf.yaml, to: /opt/flink/conf/flink-conf.yaml }