---
- name: Deploy Flink Task Manager
  include_role:
    name: container/docker/compose
  vars:
    compose:
      src: /opt/impads/containers
      name: flink-task-manager
      services:
        - name: task-manager
          image: flink:1.11.1-scala_2.12-java11
          container_name: task-manager
          command: taskmanager
          ports:
            - "6121:6121"
            - "6122:6122"
            - "6124:6124"
            - "6125:6125"
            - "40100:40100"
            - "50200:50200"
          environment:
            - JOB_MANAGER_RPC_ADDRESS={{ flink_services.flink_job_manager_address }}
            - JAVA_TOOL_OPTIONS=-javaagent:/opt/flink/jolokia-jvm-1.6.2-agent.jar=port=8778,host=0.0.0.0
          properties:
            - { src: flink-conf.yaml.j2, from: flink-conf.yaml, to: /opt/flink/conf/flink-conf.yaml }
          files:
            - { src: "{{ playbook_dir }}/../roles/metrics-monitor/agent/files/jolokia-jvm-1.6.2-agent.jar", from: jolokia-jvm-1.6.2-agent.jar, to: "/opt/flink/jolokia-jvm-1.6.2-agent.jar" }