---
- name: Deploy Kafka Streams Gira Travels Pattern
  include_role:
    name: container/docker/compose
  vars:
    compose:
      src: /opt/impads/containers
      name: kafka-stream
      services:
        - name: kafka-stream-gira-topology
          image: impads/kafka-streams-gira-travels-pattern:0.0.1
          container_name: kafka-stream
          environment:
            - JAVA_TOOL_OPTIONS=-javaagent:/opt/kafka-stream/jolokia-jvm-1.6.2-agent.jar=port=8778,host=0.0.0.0
          properties:
            - { src: gira-travels-pattern-topology.conf.j2, from: gira-travels-pattern-topology.conf.conf, to: /opt/isel/thesis/impads/spds-kafka/topology/conf/topology.conf }
          files:
            - { src: "{{ playbook_dir }}/../roles/metrics-monitor/agent/files/jolokia-jvm-1.6.2-agent.jar", from: jolokia-jvm-1.6.2-agent.jar, to: "/opt/kafka-stream/jolokia-jvm-1.6.2-agent.jar" }