---
- name: set kafka server list
  set_fact:
    kafka_server_list: "{{ kafka_server_list | default([]) + [ hostvars[item]['networkInterfaces'][0]['networkIP'] + ':' + '9092' ] }}"
  with_items:
    - "{{ groups['kafka_node'] }}"

- name: set kafka boostrap server
  set_fact:
    kafka_bootstrap_server: "{{ kafka_server_list | join(',')}}"

- name: Deploy Kafka Streams Gira Travels Pattern
  include_role:
    name: container/docker/compose
  vars:
    compose:
      src: /opt/impads/containers
      name: kafka-stream
      services:
        - name: kafka-stream-gira-topology
          image: impads/kafka-streams-gira-travels-pattern:0.0.1
          container_name: kafka-stream-gira-topology
          properties:
            - { src: gira-travels-pattern-topology.conf.j2, from: gira-travels-pattern-topology.conf.conf, to: /opt/isel/thesis/impads/spds-kafka/topology/conf/topology.conf }