agent:
    outputs:
        influxdb:
            host: ""
    docker:
        enabled: false
    statsd:
        enabled: false
    rabbitmq:
        enabled: false
        host: ""
    redis:
        enabled: false
        host: ""