---
- name: Deploy Flink Job Manager
  include_role:
    name: container/docker/compose
  vars:
    compose:
      src: /opt/impads/containers
      name: flink-job-manager
      services:
        - name: job-manager
          image: flink:1.11.1-scala_2.12-java11
          container_name: job-manager
          command: jobmanager
          ports:
            - "8081:8081"
            - "6123:6123"
            - "6124:6124"
            - "6125:6125"
            - "50200:50200"
          environment:
            - JOB_MANAGER_RPC_ADDRESS={{ flink_services.flink_job_manager_address }}
          properties:
            - { src: flink-conf.yaml.j2, from: flink-conf.yaml, to: /opt/flink/conf/flink-conf.yaml }