---
- name: Deploy Strom Nimbus
  include_role:
    name: container/docker/compose
  vars:
    compose:
      src: /opt/impads/containers
      name: storm
      services:
        - name: zookeeper
          image: bitnami/zookeeper:3.6.1
          container_name: zookeeper
          environments:
            - ALLOW_ANONYMOUS_LOGIN=yes
        - name: nimbus
          image: impads/storm:2.2.0
          container_name: nimbus
          command: storm nimbus
          ports:
            - "6627:6627"
            - "8000:8000"
          properties:
            - { src: storm.yaml.j2, from: storm.yaml, to: /conf/storm.yaml }
        - name: nimbus-ui
          image: impads/storm:2.2.0
          container_name: nimbus-ui
          command: storm ui
          ports:
            - "8080:8080"
          properties:
            - { src: storm.yaml.j2, from: storm.yaml, to: /conf/storm.yaml }