---
- name: Deploy Strom Nimbus
  include_role:
    name: container/docker/compose
  vars:
    compose:
      src: /opt/impads/containers
      name: storm
      services:
        - name: supervisor
          image: impads/storm:2.2.0
          container_name: supervisor
          command: storm supervisor
          ports:
            - "8000:8000"
            - "6700:6700"
            - "6701:6701"
            - "6702:6702"
            - "6703:6703"
            - "6704:6704"
            - "6705:6705"
            - "6706:6706"
            - "6707:6707"
          environment:
            - JAVA_TOOL_OPTIONS=-javaagent:/opt/flink/jolokia-jvm-1.6.2-agent.jar=port=8778,host=0.0.0.0
          properties:
            - { src: storm.yaml.j2, from: storm.yaml, to: /conf/storm.yaml }
          files:
            - { src: "{{ playbook_dir }}/../roles/metrics-monitor/agent/files/jolokia-jvm-1.6.2-agent.jar", from: jolokia-jvm-1.6.2-agent.jar, to: "/opt/flink/jolokia-jvm-1.6.2-agent.jar" }