---
- name: Deploy Strom Nimbus
  include_role:
    name: container/docker/compose
  vars:
    compose:
      src: /opt/impads/containers
      name: storm
      services:
        - name: supervisor
          image: impads/storm:2.2.0
          container_name: supervisor
          command: storm supervisor
          ports:
            - "8000:8000"
            - "6700:6700"
            - "6701:6701"
            - "6702:6702"
            - "6703:6703"
          properties:
            - { src: storm.yaml.j2, from: storm.yaml, to: /conf/storm.yaml }